trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'juego3y2-dockerhub'
    repository: 'bujosa2020/juegocartas3y2'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
